name: Request_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.PlatformApi.Request/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.PlatformApi.Request
      env_var_name_1: APPLICATION_ID
      env_var_name_2: CLIENT_SECRET
      env_var_name_3: TENANT_URL
    secrets:
      badge_service_api_key: ${{ secrets.platformApiApplicationId }}
      env_var_value_1: ${{ secrets.APPLICATION_ID }}
      env_var_value_2: ${{ secrets.CLIENT_SECRET }}
      env_var_value_3: ${{ secrets.TENANT_URL }}
